### ISSUE TITLE
cannot distinguish the difference between the execution results of these two run.py commands.

### ISSUE THREAD

**Issue by jenovasephiroth** [DL4mHealth/Medformer#1]
When I interrupt the execution of the Medformer.sh task and query the execution progress in the result file, I cannot distinguish the difference between the execution results of these two run.py commands.

such as:
when i run this job
# ADFD Dataset
python \
  -u run.py \
  --task_name classification \
  --is_training 1 \
  --root_path ./dataset/ADFD/ \
  --model_id ADFD-Indep \
  --model Medformer \
  --data ADFD \
  --e_layers 6 \
  --batch_size 128 \
  --d_model 128 \
  --d_ff 256 \
  --patch_len_list 2,4,8,8,16,16,16,16,32,32,32,32,32,32,32,32 \
  --augmentations drop0.5 \
  --swa \
  --no_inter_attn \
  --des 'Exp' \
  --itr 5 \
  --learning_rate 0.0001 \
  --train_epochs 100 \
  --patience 10
python \
  -u run.py \
  --task_name classification \
  --is_training 1 \
  --root_path ./dataset/ADFD/ \
  --model_id ADFD-Indep \
  --model Medformer \
  --data ADFD \
  --e_layers 6 \
  --batch_size 128 \
  --d_model 128 \
  --d_ff 256 \
  --patch_len_list 2,4,8,8,16,16,16,16,32,32,32,32,32,32,32,32 \
  --augmentations none \
  --swa \
  --des 'Exp' \
  --itr 5 \
  --learning_rate 0.0001 \
  --train_epochs 100 \
  --patience 10

i get a result logs is:
classification_ADFD-Indep_Medformer_ADFD_ftM_sl96_ll48_pl96_dm128_nh8_el6_dl1_df256_fc1_ebtimeF_dtTrue_Exp_seed41  
classification_ADFD-Indep_Medformer_ADFD_ftM_sl256_ll48_pl0_dm128_nh8_el6_dl1_df256_fc1_ebtimeF_dtTrue_Exp_seed42  
classification_ADFD-Indep_Medformer_ADFD_ftM_sl256_ll48_pl0_dm128_nh8_el6_dl1_df256_fc1_ebtimeF_dtTrue_Exp_seed43  
classification_ADFD-Indep_Medformer_ADFD_ftM_sl256_ll48_pl0_dm128_nh8_el6_dl1_df256_fc1_ebtimeF_dtTrue_Exp_seed44  
classification_ADFD-Indep_Medformer_ADFD_ftM_sl256_ll48_pl0_dm128_nh8_el6_dl1_df256_fc1_ebtimeF_dtTrue_Exp_seed45 

It is impossible to distinguish the execution results of these two run.py commands

**Comment by YiheWang** [comment]
Yes, you are right. Since our code includes all the baseline methods, any parameters belonging to a specific method are not included in the log name, such as "--stride", "--augmentations", or "--no_inter_attn". Only the parameters shared among all the methods are recorded automatically in the logs. 

The "--itr" is set to 5, which means running 5 times (seed41-45) for each script line. So if we want to distinguish the results for multiple script lines, what we did during parameter tuning was just record these specific parameters down manually in order every 5 lines of results  _(:з」∠)_.).

**Comment by jenovasephiroth** [comment]
How to continue executing the remaining Medformer.sh tasks?
Or i need to re-execute everything

**Comment by YiheWang** [comment]
You can delete any command lines you have already run in the script. Counting from the beginning, each script line will get 5 results for seeds 41-45. For dataset ADFD under subject-independent setup, there is one main experiment script and three scripts for ablation study. We have included all the script lines for the experiments detailed in our paper, including the ablation study, as a reference. Running all the scripts in the Medformer.sh file can be time-consuming.

If you do not want to reproduce all the results from our paper, it is sufficient to run only the scripts for the specific tasks you are interested in. Creating a temporary shell file to contain only the necessary scripts and running it may be a good choice.

**Comment by jenovasephiroth** [comment]
no

I found that if I run the task directly, the results of ablation study overwrite the results of training.


It is recommended not to save each run.py task in the same result, not just the log and results.

**Comment by YiheWang** [comment]
Thanks for the suggestion. We will try to update our code later
to distinguish different tasks in the same method.

Best regards,
Yihe Wang
