### ISSUE TITLE
TDBRAIN_participants_V2.tsv file

### ISSUE THREAD

**Issue by Xi-Mu-Yu** [DL4mHealth/Medformer#10]
Hello, I would like to sincerely thank you for your valuable work on this project! While working with the TDBrain dataset, I encountered a small issue. Could you please let me know how I can obtain the TDBRAIN_participants_V2.tsv file? Any guidance or instructions on how to access it would be greatly appreciated.Thank you again for your contribution, and I look forward to hearing from you.

**Comment by YiheWang** [comment]
Hi, in the download page, you can click the _the participants datasheets_ link in the first line for downloading. For your reference, I attached the screenshot.

<img width="532" alt="3bb553a4c7f14af1232f3239655fbcc" src="https://github.com/user-attachments/assets/2785c0bf-d17e-47c3-a2f8-c4f107532320" />

**Comment by Xi-Mu-Yu** [comment]
![db68ad13-427c-48fa-bf14-b7e822206485](https://github.com/user-attachments/assets/29b9e2a4-8b2e-4883-a1cf-cc1be759e8a0)

It seems that I have encountered a network issue, and I have been trying for a long time but still cannot access it. Could you please send the TDBRAIN_participants_V2.tsv file to my email? My email is huming708@gmail.com.
Thank you

**Comment by YiheWang** [comment]
Sure. No problem. Check the email to see if you receive it.

**Comment by Xi-Mu-Yu** [comment]
"I've received everything, thank you so much for your work and the help you've provided. I look forward to seeing even better work from you in the future."

**Comment by pengjuRen99** [comment]
I also encountered the same problem. Could you please send me a copy of TDBrain data? My email address is: pengjuren99@163.com. Thank you very much !

**Comment by Xi-Mu-Yu** [comment]
> I also encountered the same problem. Could you please send me a copy of TDBrain data? My email address is: [pengjuren99@163.com](mailto:pengjuren99@163.com). Thank you very much !

I've sent it to you, did you receive it

**Comment by YiheWang** [comment]
Hi, I can only send you the tsv file. The complete TDBrain dataset is huge (over 90GB) and impossible to send via email, and I cannot send it to you directly according to the rules of using this dataset. Check your email to see if you receive it.

**Comment by pengjuRen99** [comment]
Thank you very much for your sharing. I have received it.
