### ISSUE TITLE
 can you write a.py file for inference.

### ISSUE THREAD

**Issue by lindouer** [DL4mHealth/Medformer#2]
Hi, I've got the model of the.pth file, but I don't know how to infer, can you write a.py file for inference.

**Comment by YiheWang** [comment]
Hi, you can simply set "--is_training 0".

For example, if the command line for training is: 
`python -u run.py --task_name classification --is_training 1 --root_path ./dataset/APAVA/ --model_id APAVA-Indep --model Medformer --data APAVA --e_layers 6 --batch_size 32 --d_model 128 --d_ff 256 --patch_len_list 2,2,2,4,4,4,16,16,16,16,32,32,32,32,32 --augmentations none,drop0.35 --swa --des 'Exp' --itr 5 --learning_rate 0.0001 --train_epochs 100 --patience 10`

You can infer the result by command line:
`python -u run.py --task_name classification --is_training 0 --root_path ./dataset/APAVA/ --model_id APAVA-Indep --model Medformer --data APAVA --e_layers 6 --batch_size 32 --d_model 128 --d_ff 256 --patch_len_list 2,2,2,4,4,4,16,16,16,16,32,32,32,32,32 --augmentations none,drop0.35 --swa --des 'Exp' --itr 5 --learning_rate 0.0001 --train_epochs 100 --patience 10`
