### ISSUE TITLE
A few questions about Medformer

### ISSUE THREAD

**Issue by lindouer** [DL4mHealth/Medformer#4]
Hello,
I really appreciate what you've done with Medformer, and I have a few questions for you about Medformer.
I have been doing some experiments recently to improve the effect of the PTB-XL dataset in Medformer, so I came up with the method of ECG data enhancement. I have successively tried Safdar et al. - 2023 - A novel data augmentation approach for me Enhancement. PDF https://github.com/mfarhan166/ECG-data-augmentation/blob/main/Data_Augmentation_algorithm_latest.ip in this paper Ynb and https://github.com/mfarhan166/ECG-data-augmentation/blob/main/revised-augmentation/Improved_ECG_DA_v3_For_ECG_v2.ipy nb These two algorithms enhanced the data, and then put them into Medformer for experiments. The experimental results obtained twice were 20% worse than the original experimental results in the Medformer paper. I would like to ask you if you have any good suggestions for my experiment.

My experimental steps are as follows: 1. Convert PTB-XL500 Hz downloaded from the official website into numpy two-dimensional array (this is the data preprocessing required by data enhancement algorithm) 2. After pretreatment algorithm of data in the enhancement of new PTB - XL3. Will enhance the PTB - XL again after processing to make it meet the Medformer of PTB - XL data requirements (we are reference https://github.com/DL4mHealth/Medformer/blob /main/data_preprocessing/PTB-XL_preprocessing.
The resulting experiment is shown below:
![image](https://github.com/user-attachments/assets/8d15c3d6-970d-4e9b-be7c-23c6c4d07815)

**Comment by YiheWang** [comment]
```
import torch
import torch.nn as nn


class Jitter(nn.Module):
    # apply noise on each element
    def __init__(self, scale=0.1):
        super().__init__()
        self.scale = scale

    def forward(self, x):
        if self.training:
            x += torch.randn_like(x) * self.scale
        return x


class Scale(nn.Module):
    # scale each channel by a random scalar
    def __init__(self, scale=0.1):
        super().__init__()
        self.scale = scale

    def forward(self, x):
        if self.training:
            B, C, T = x.shape
            x *= 1 + torch.randn(B, C, 1, device=x.device) * self.scale
        return x


class Flip(nn.Module):
    # left-right flip
    def __init__(self, prob=0.5):
        super().__init__()
        self.prob = prob

    def forward(self, x):
        if self.training and torch.rand(1) < self.prob:
            return torch.flip(x, [-1])
        return x


class Shuffle(nn.Module):
    # shuffle channels order
    def __init__(self, prob=0.5):
        super().__init__()
        self.prob = prob

    def forward(self, x):
        if self.training and torch.rand(1) < self.prob:
            B, C, T = x.shape
            perm = torch.randperm(C)
            return x[:, perm, :]
        return x


class FrequencyMask(nn.Module):
    def __init__(self, ratio=0.1):
        super().__init__()
        self.ratio = ratio

    def forward(self, x):
        if self.training:
            B, C, T = x.shape
            # Perform rfft
            x_fft = torch.fft.rfft(x, dim=-1)
            # Generate random indices for masking
            mask = torch.rand(x_fft.shape, device=x.device) > self.ratio
            # Apply mask
            x_fft = x_fft * mask
            # Perform inverse rfft
            x = torch.fft.irfft(x_fft, n=T, dim=-1)
        return x


def get_augmentation(augmentation):
    if augmentation.startswith("jitter"):
        if len(augmentation) == 6:
            return Jitter()
        return Jitter(float(augmentation[6:]))
    elif augmentation.startswith("scale"):
        if len(augmentation) == 5:
            return Scale()
        return Scale(float(augmentation[5:]))
    elif augmentation.startswith("drop"):
        if len(augmentation) == 4:
            return nn.Dropout(0.1)
        return nn.Dropout(float(augmentation[4:]))
    elif augmentation.startswith("flip"):
        if len(augmentation) == 4:
            return Flip()
        return Flip(float(augmentation[4:]))
    elif augmentation.startswith("shuffle"):
        if len(augmentation) == 7:
            return Shuffle()
        return Shuffle(float(augmentation[7:]))
    elif augmentation.startswith("frequency"):
        if len(augmentation) == 9:
            return FrequencyMask()
        return FrequencyMask(float(augmentation[9:]))
    elif augmentation == "none":
        return nn.Identity()
    else:
        raise ValueError(f"Unknown augmentation {augmentation}")
```


Hi, we came up with some new augmentation methods; please add them to your code and use a combination of them. According to our experiments, avoid using **Scale**; it usually damages the results. You can combine your own augmentation methods with these methods together. If you augment the data before training during preprocessing, my suggestion is to mix the augmented samples with raw samples and avoid using augmented samples only. 

Besides, it looks like your screenshot just ran 5 epochs yet; how about trying more epochs?

**Comment by YiheWang** [comment]
A training suggestion for PTB-XL. Since it is very large, if you are short of computing resources, you could tune your code and parameters on a subset, for example, 10%-20% of the whole dataset. 

Additionally, there are many public ECG datasets available that you could explore as alternatives for PTB-XL. For example, It seems like the authors with PTB-XL came up with a new dataset called PTB-XL+. Trying our method on different datasets is also an interesting research direction to explore.

**Comment by lindouer** [comment]
Thank you for your suggestions. I will try them all

**Comment by lindouer** [comment]
Thank you very much for your advice, which has inspired me a lot. I will try it
&nbsp;


林逗儿
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Yihe ***@***.***&gt;; 
发送时间: 2024年8月2日(星期五) 中午11:20
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [DL4mHealth/Medformer] A few questions about Medformer (Issue #4)















PTB-XL的培训建议。由于它非常大，如果您缺少计算资源，您可以在一个子集上调整代码和参数，例如，占整个数据集的10%-20%。

-
直接回复这封邮件，在GitHub上查看，或取消订阅.
***@***.***&gt;
