### ISSUE TITLE
Question regarding Medformer and Encoder-only models

### ISSUE THREAD

**Issue by xinformatics** [DL4mHealth/Medformer#5]
Hi Authors, 

Congratulations on the great work. I would like to know how you modified the forecasting-based methods for classification.

Did you extract the Encoder-only part and use it for classification? (I think this is true based on Appendix C), please correct me if I am wrong.

Also, if you used the encoder-only parts for all transformer variants, could you share the Encoder-only model implementation or teach me how to extract them? I would like to test your approach + other models on some of the in-house clinical time series data.

Thank you

**Comment by YiheWang** [comment]
Hi, please refer to the [Time-Series-Library](https://github.com/thuml/Time-Series-Library) repository for the implementation of classification tasks in other models. Our code is built upon their framework.

From our understanding, they primarily use the encoder-only variant for these methods with minor modifications when doing classification tasks. There is no need to explicitly extract this part; the encoder-only model will be automatically applied when running a classification task by passing the `--task_name classification` argument in the command line.  

Check each model in the `models` folder. Different tasks, such as forecasting and classification, have different code implementations. We have also provided all the scripts for the classification task in the `scripts/classification` folder.

**Comment by xinformatics** [comment]
Thank you so much for the clarification.
