### ISSUE TITLE
Questions about your paper

### ISSUE THREAD

**Issue by dyhan316** [DL4mHealth/Medformer#6]
Thank you so much for the amazing paper! 

We stumbled upon your paper while researching for ways to make our iEEG model incorporate various timescale/patch-sizes (and was very glad to see the paper :) ) 

We have a few questions if you don't mind! 

**1. Does you model support varying numbers of channels?** : While your new tokenization method seems great, especially for medical time series, it seems that this would not enable running the model on varying numbers of channels? 

**2. Have you tried multi-head attention in place of using multiple instances of the same patch length?** : I think that one reason why using multiple instances of the same patch sizes works well is because having many routers for the same patch length enables more detailed analysis by the model for a given patch length. However, it seems that multi-head attention can achieve a similar thing, and was wondering if you have compared the two! 

**3. Are routers better than Fourier-based models at modeling spectral components?** : You mentioned that one of the reasons for using multiple patches is due to the multi-scale and periodic property of the EEG and ECG. Given that there are other frequency-aware models (ex ; FreTS), we were wondering if you've tried them. 

**4. Choice of patch sizes** : Was there a reason for testing patch sizes from 2 to 32? Since the EEG data used was 256Hz,  patch sizes of 2 to 32 seems to equate to modeling frequencies from 128 Hz to 8Hz, which while is a wide range does not include lower frequency ranges (i.e. Theta waves and Delta waves)

**5. Was the position embedding scaled?** : It seems that regardless of the patch size, the same position embedding was used. However, since the actual position in time of each patch would be different depending on the patch size, it seems that this may not be the most optimal method?

**6. Bottleneck in the router?** : It seems that Medformer could be seen as training multiple transformer blocks for each patch size, then linking them together using the router. While this method seems good, we were just wondering if this could act as a sort of a bottleneck of information between the patches? 

Thank you in advance for your answers! Really!!

**Comment by YiheWang** [comment]
1) Our model currently cannot train on multiple time series datasets simultaneously when they have different numbers of channels. If you are looking for large EEG models, recent research suggests that one way to handle datasets with varying channel counts is to flatten all channels and concatenate them into a single series. By preprocessing data in this way, our model can be trained on datasets with differing channel counts.

2) We do incorporate multi-head self-attention in our model. While multiple instances of the same patch size may perform similarly to multi-head self-attention, they also allow for applying different augmentation methods. Different instances of the same patch length with different augmentations can learn from each other, which may intuitively enhance the model’s learning capability at that specific granularity.

3) We are not entirely certain about the application of frequency-based methods in our context. However, preliminary experiments using frequency-based models like FEDformer showed instability and poor performance in classifying medical time series. If you have specific recommendations for models employing frequency-based techniques, we would be happy to explore and test them in future work.

4) The selection of patch sizes was based on ablation studies and parameter tuning. We also considered this question during the paper-writing process. A patch length of 2 does not necessarily imply learning features only around 128Hz. For instance, the iTransformer uses the entire series as a token, which does not preclude it from learning temporal features.

5) The positional embedding operates differently from varying patch lengths. It forms a very long sequence, and only the initial portion—corresponding to the number of patches—is added to the patch embeddings. For more details, please refer to the implementation of `PositionalEmbedding` in `Embed.py`.

6) The embedding and self-attention blocks are separated for each patch size, while the feed-forward and layernorm layers are shared. Using routers to communicate among granularities balances complexity and performance, as discussed in the paper. Besides, we believe that cross-channel patching is the most significant design of Medformer, not the router mechanism. According to the ablation study, using cross-channel patching significantly outperforms single-channel patching in effectiveness.

We are happy to provide more details if you have any further questions.

**Comment by dyhan316** [comment]
Thank you so much for your quick and detailed response! It's really helpful :) (it's really really helpful really!)

We have a few tangential questions regarding the paper if you don't mind. 

1. **Do you think that training separate patch-lengths would be possible?** : I don't know if I am correct, but it seems that your method would enable training different granularities separately (i.e. instead of training patch-lengths 2,4,8,16 together, training 2,4 together, 2,8,16 together, and so on)(i.e. kind of like what iTransformer did with variables). Would this be possible, and if so, do you think that this would enable the model to extract information from different patch-lengths more effectively and also reduce memory footprint? 

2. **Do you think that augmentation would be a necessary part of the model, even when the amount of data is massive?** : In other words, do you think that augmentation acts as regularization to make the model perform better in low-data situations, or do you think that augmentation is necessary for the model to work better? We are asking because comparing PTB to PTB-XL in Table 5 seems to imply that when there's more data, the performance degradation from having no augmentation decreases significantly. 

Again, thank you in advance for your response :) !

**Comment by YiheWang** [comment]
1) If your question pertains to the combination of patch lengths, it is highly flexible. For instance, you can use combinations like 1, 16, 64, or 2, 3, 4. The only constraint is that the patch length must be less than half of the total series length, otherwise the self-attention is meaningless.

2) Augmentation is not strictly necessary, and an inadequate combination of augmentation methods can even degrade performance. However, based on our experience from previous works, applying basic augmentations like timestamp masking is generally beneficial, even when you have sufficient data. Additionally, different augmentations can enhance the model's ability to learn across granularities by using routers, as mentioned earlier.

**Comment by dyhan316** [comment]
Thank you for your quick response!

Regarding the first question, I was asking if training subsets of all the patch sizes for each iteration instead of jointly training them all together was possible to reduce memory size. For example, instead of training with all patch sizes 2,4,8,16, would it be possible to train on patch sizes 2,4,8 for the first iteration, then patch size 2,8,16 for the second iteration and so on?

**Comment by YiheWang** [comment]
I guess no. That sounds like a good way to save memory. You need to modify the code to achieve such a training method.

**Comment by dyhan316** [comment]
I see! So to be clear, it's possible on paper, but the code needs to be changed?

**Comment by YiheWang** [comment]
I think it is possible, but you need to figure out how to "turn off" some patch length during training. Currently, I have no idea how to achieve this functionality.

**Comment by dyhan316** [comment]
I see! Thank you for the response :)
