### ISSUE TITLE
Problems encountered in reproducing medformer

### ISSUE THREAD

**Issue by devin-21** [DL4mHealth/Medformer#8]
Hello yihe, thanks for this innovative paper!

I'm having some problems reproducing the metrics of the paper, can you help me identify where the problem might be?
Here are the steps I implemented

Environment preparation
```
git clone https://github.com/DL4mHealth/Medformer.git
cd Medformer
conda create -n medformer python==3.8
conda activate medformer
pip install -r requirements.txt
```

Run the Medformer train and eval script (using datasets downloaded from README.md, e.g. PTB, PTB-XL, APAVA, ADFTD)
`bash scripts/classification/Medformer.sh`

Here is my result:
![image](https://github.com/user-attachments/assets/c1939d00-3dcd-47ea-99af-ab2bcc392257)
On the left are my reproduction results, on the right the results reported by **Medformer** paper

I would like to ask if there is anything I missed or did wrong in the steps of reproduction? I would greatly appreciate if you could help me locate it.

Thanks again for the code base & insightful paper!

**Comment by YiheWang** [comment]
Hi, everything looks good to me. It might be caused by the machine difference. We run on an RTX 4090 GPU for all experiments except PTB-XL. The PTB-XL runs on a 4-A5000 cluster. 

To make sure I did not put the wrong parameters in bash scripts, let me rerun the ADFTD for a test and get back to you later.

**Comment by devin-21** [comment]
Thanks for the reply and confirmation of the parameters! I forgot to mention before that all my reproductions were done on a single A100, so if the parameters are fine I think it may indeed be a different machine that is causing the error.

**Comment by YiheWang** [comment]
Hi, I rerun the ADFTD and get the same results. The scripts should be correct. For your reference, I attached the checkpoints of ADFTD with subject-independent setups: [Link](https://drive.google.com/drive/folders/1rOYKqIYDRSXiIQCqZZKT8xGFtePWngRa?usp=drive_link )

--patch_len_list 2,4,8,8,16,16,16,16,32,32,32,32,32,32,32,32 --augmentations drop0.5
classification_ADFTD-Indep_Medformer_ADFTD_ftM_sl96_ll48_pl96_dm128_nh8_el6_dl1_df256_fc1_ebtimeF_dtTrue_Exp_seed41  
Validation results --- Loss: 4.48621, Accuracy: 0.52981, Precision: 0.51736, Recall: 0.51436, F1: 0.51212, AUROC: 0.67273, AUPRC: 0.51911
Test results --- Loss: 3.30192, Accuracy: 0.53338, Precision: 0.50843, Recall: 0.50707, F1: 0.50647, AUROC: 0.71146, AUPRC: 0.50180

classification_ADFTD-Indep_Medformer_ADFTD_ftM_sl256_ll48_pl0_dm128_nh8_el6_dl1_df256_fc1_ebtimeF_dtTrue_Exp_seed42  
Validation results --- Loss: 5.51230, Accuracy: 0.54666, Precision: 0.54656, Recall: 0.52903, F1: 0.52708, AUROC: 0.68171, AUPRC: 0.54909
Test results --- Loss: 3.86598, Accuracy: 0.55031, Precision: 0.53131, Recall: 0.53305, F1: 0.53080, AUROC: 0.72947, AUPRC: 0.52832

classification_ADFTD-Indep_Medformer_ADFTD_ftM_sl256_ll48_pl0_dm128_nh8_el6_dl1_df256_fc1_ebtimeF_dtTrue_Exp_seed43  
Validation results --- Loss: 1.47830, Accuracy: 0.53561, Precision: 0.54536, Recall: 0.52261, F1: 0.51759, AUROC: 0.68217, AUPRC: 0.53457
Test results --- Loss: 1.33527, Accuracy: 0.54369, Precision: 0.52071, Recall: 0.51016, F1: 0.50941, AUROC: 0.69908, AUPRC: 0.52791

classification_ADFTD-Indep_Medformer_ADFTD_ftM_sl256_ll48_pl0_dm128_nh8_el6_dl1_df256_fc1_ebtimeF_dtTrue_Exp_seed44  
Validation results --- Loss: 4.83239, Accuracy: 0.53977, Precision: 0.52881, Recall: 0.52794, F1: 0.52458, AUROC: 0.67367, AUPRC: 0.54064
Test results --- Loss: 3.70699, Accuracy: 0.50519, Precision: 0.48451, Recall: 0.48558, F1: 0.48385, AUROC: 0.69555, AUPRC: 0.49838

classification_ADFTD-Indep_Medformer_ADFTD_ftM_sl256_ll48_pl0_dm128_nh8_el6_dl1_df256_fc1_ebtimeF_dtTrue_Exp_seed45  
Validation results --- Loss: 4.11096, Accuracy: 0.52476, Precision: 0.51947, Recall: 0.50977, F1: 0.50757, AUROC: 0.66517, AUPRC: 0.51001
Test results --- Loss: 3.07686, Accuracy: 0.53086, Precision: 0.50624, Recall: 0.49970, F1: 0.50191, AUROC: 0.71091, AUPRC: 0.50394

**Comment by devin-21** [comment]
Hi, I saw your results, that may indeed be due to machine differences, I found an RTX 4090 that basically reproduces the metrics reported in the paper!
Thanks again for helping me find the problem in the reproduction!
