### ISSUE TITLE
Hello, if I want to run the Medformer model on a dataset consisting of 2000 csv tables, how should I proceed, and how should I modify your code?

### ISSUE THREAD

**Issue by lindouer** [DL4mHealth/Medformer#9]
Hello, if I want to run the Medformer model on a dataset consisting of 2000 csv tables, how should I proceed, and how should I modify your code?

**Comment by YiheWang** [comment]
Hi, a simple way is to process your dataset into the same format as ours. Then write a dataloader class in dataloader.py to load your processed dataset. Finally, add and name your new dataloader class into data_factory.py. Now you can call your dataloader in parser argument with `--data`.

If you need to be more specific,  give me more details about your raw datasets, and then I can guide you on how to write your data processing file.

**Comment by lindouer** [comment]
Thank you very much for your suggestion. I'll give it a try
